#-----------------------------------------------
# srclist.mk
# This file is automatically generated, don't try to edit it
# all modifications will be lost with next build
#-----------------------------------------------
ARCH := arm
TARGET = crm
BASEBOARD := G327
# Listing C/C++ source files here. (C dependencies are automatically generated.)
SRC += .\cgen\__GS_driverapi.c 
SRC += .\cgen\MCQ_dev.c 
SRC += .\cgen\RCColor.c 
SRC += .\cgen\RCText.c 
SRC += .\cgen\gdsPrjUserCInfo_CM.c 
SRC += .\cgen\gdsPrjUserCInfo_VR.c 
SRC += crm.c 
SRC += Backup.c 
SRC += bnso.c 
SRC += calibr_omfb.c 
SRC += commands.c 
SRC += control.c 
SRC += ctrl_brush.c 
SRC += ctrl_front_attach.c 
SRC += ctrl_inter_attach.c 
SRC += ctrl_light.c 
SRC += ctrl_manipulator.c 
SRC += ctrl_plough.c 
SRC += ctrl_side_attach.c 
SRC += ctrl_top_adrive.c 
SRC += ctrl_top_adrive_feedback.c 
SRC += ctrl_top_attachment_cr.c 
SRC += ctrl_top_attachment_cr600.c 
SRC += ctrl_top_conveyor.c 
SRC += ctrl_top_spread_disk.c 
SRC += ctrl_top_summer_attachment.c 
SRC += ctrl_top_winter_attachment.c 
SRC += debug_log.c 
SRC += drawfunction.c 
SRC += gs_easy_config.c 
SRC += gs_easy_config_menu.c 
SRC += gse_msgbox.c 
SRC += gseerrorlist.c 
SRC += gselist.c 
SRC += gsemaint.c 
SRC += gsemaint_lifetime.c 
SRC += gsemaint_runtime.c 
SRC += gsemcm.c 
SRC += gsescrolllist.c 
SRC += hydvalvectrl.c 
SRC += io.c 
SRC += io_joystick_v85_b25.c 
SRC += io_types.c 
SRC += j1939.c 
SRC += okb600.c 
SRC += param.c 
SRC += pinout.c 
SRC += profile.c 
SRC += response_error.c 
SRC += rtr_uh.c 
SRC += sql_table.c 
SRC += top_summer_attachment.c 
SRC += userj1939.c 
SRC += usr_tools.c 
SRC += visu.c 
SRC += visu_ctrl.c 
SRC += visu_error.c 
SRC += visu_io.c 
SRC += visu_learning.c 
SRC += visu_main.c 
SRC += visu_material.c 
SRC += visu_mcm_config.c 
SRC += visu_menu.c 
SRC += visu_param.c 
SRC += visu_pinout.c 
SRC += visu_profile.c 
SRC += visu_properties.c 
SRC += visu_sensors.c 
SRC += visu_spreadsettings.c 
SRC += visu_start.c 
SRC += visu_statistik.c 
# Debug options
FLAG_DEBUG = 1
FLAG_WINSIMU = 1
# Listing additional object files here.
ADDOBJ = 
LIBS = CanOpenSlaveStack-DSeriesS config-so curlS gsDebugS fpgaS iniS logS mbedcryptoS mbedtlsS mbedx509S gsNetwork-sslS gsSocket-sslS sqliteS gsThreadS gsUsbHidS gsUsbSerS UserCAPIS gsUtilS hiddi 
LIBDIRS = 
